# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {
    "say_hello": "00_core.ipynb",
    "get_stencil": "010_finite_diff.ipynb",
    "apply_stencil": "010_finite_diff.ipynb",
}

modules = ["core.py", "finite_diff.py"]

doc_url = "https://d-chambers.github.io/splashy/"

git_url = "https://github.com/d-chambers/splashy/tree/master/"


def custom_doc_links(name):
    return None
